from rest_framework_simplejwt.views import TokenObtainPairView
from .token_serializers import CustomTokenObtainPairSerializer

class customEmailObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer