# Generated by Django 5.2.7 on 2025-11-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='satus_notified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'L1 Cleared'), ('interview_technical', 'Technical Cleared'), ('hr_cleared', 'HR Cleared'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('onhold', 'OnHold')], default='applied', max_length=20),
        ),
    ]
