# Generated by Django 5.2.7 on 2025-11-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_satus_notified_jobapplication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='satus_notified',
            new_name='status_notified',
        ),
    ]
